quiz_data = {
    "General Knowledge": [
        {"question": "What is the capital of France?", "choices": ["Paris", "London", "Berlin", "Madrid"], "answer": "Paris"},
        {"question": "Which planet is known as the Red Planet?", "choices": ["Earth", "Mars", "Jupiter", "Venus"], "answer": "Mars"},
        {"question": "What is the largest ocean on Earth?", "choices": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], "answer": "Pacific Ocean"},
        {"question": "Who wrote 'Hamlet'?", "choices": ["Charles Dickens", "Mark Twain", "William Shakespeare", "Jane Austen"], "answer": "William Shakespeare"},
        {"question": "What is the smallest country in the world?", "choices": ["Monaco", "Vatican City", "San Marino", "Nauru"], "answer": "Vatican City"},
        {"question": "Which country is known as the Land of the Rising Sun?", "choices": ["China", "Japan", "Thailand", "South Korea"], "answer": "Japan"},
        {"question": "What is the tallest mountain in the world?", "choices": ["K2", "Kangchenjunga", "Lhotse", "Mount Everest"], "answer": "Mount Everest"},
        {"question": "Which element has the chemical symbol 'O'?", "choices": ["Gold", "Oxygen", "Osmium", "Hydrogen"], "answer": "Oxygen"},
        {"question": "In which year did the Titanic sink?", "choices": ["1910", "1912", "1914", "1916"], "answer": "1912"},
        {"question": "What is the hardest natural substance on Earth?", "choices": ["Gold", "Diamond", "Iron", "Titanium"], "answer": "Diamond"},
    ],
    "Science": [
        {"question": "What is the chemical symbol for water?", "choices": ["H2O", "O2", "CO2", "NaCl"], "answer": "H2O"},
        {"question": "Which gas is essential for us to breathe?", "choices": ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"], "answer": "Oxygen"},
        {"question": "What part of the cell contains the genetic material?", "choices": ["Cytoplasm", "Nucleus", "Cell membrane", "Mitochondria"], "answer": "Nucleus"},
        {"question": "What is the process of converting light energy into chemical energy called?", "choices": ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"], "answer": "Photosynthesis"},
        {"question": "What is the main gas found in the air we breathe?", "choices": ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"], "answer": "Nitrogen"},
        {"question": "Which part of the plant conducts photosynthesis?", "choices": ["Roots", "Stem", "Leaves", "Flowers"], "answer": "Leaves"},
        {"question": "What is the powerhouse of the cell?", "choices": ["Nucleus", "Mitochondria", "Ribosome", "Endoplasmic Reticulum"], "answer": "Mitochondria"},
        {"question": "What is the most abundant element in the universe?", "choices": ["Helium", "Hydrogen", "Oxygen", "Carbon"], "answer": "Hydrogen"},
        {"question": "What is the main function of red blood cells?", "choices": ["Transport nutrients", "Fight infections", "Carry oxygen", "Coagulate blood"], "answer": "Carry oxygen"},
        {"question": "Which organ in the human body is responsible for pumping blood?", "choices": ["Lungs", "Heart", "Liver", "Kidneys"], "answer": "Heart"},
    ],
    "Math": [
        {"question": "What is 7 + 6?", "choices": ["12", "13", "14", "15"], "answer": "13"},
        {"question": "What is the square root of 64?", "choices": ["6", "7", "8", "9"], "answer": "8"},
        {"question": "What is 15 * 3?", "choices": ["45", "30", "60", "75"], "answer": "45"},
        {"question": "What is 100 divided by 4?", "choices": ["20", "25", "30", "35"], "answer": "25"},
        {"question": "What is the value of Pi (π) approximately?", "choices": ["3.14", "3.15", "3.16", "3.17"], "answer": "3.14"},
        {"question": "What is 5 squared?", "choices": ["10", "15", "20", "25"], "answer": "25"},
        {"question": "What is the next prime number after 7?", "choices": ["9", "10", "11", "12"], "answer": "11"},
        {"question": "What is the value of 2^3?", "choices": ["6", "7", "8", "9"], "answer": "8"},
        {"question": "If a triangle has a base of 4 and height of 3, what is its area?", "choices": ["6", "10", "12", "15"], "answer": "6"},
        {"question": "What is 9 + 10?", "choices": ["18", "19", "20", "21"], "answer": "19"},
    ]
}
